version: "2"
services:
  qbittorrent:
    image: linuxserver/qbittorrent:4.5.5
    container_name: qbittorrent
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Asia/Shanghai
      - UMASK_SET=022
      - WEBUI_PORT=8081 
    volumes:
      - ./var/qBittorrent/config:/config 
      - ./downloads:/downloads 
    ports:
      - 6881:6881
      - 6881:6881/udp
      - 8081:8081
    restart: unless-stopped
    networks:
      animeNetwork:
        ipv4_address: 172.172.0.2
  autoanime:
    restart: always
    image: heasonnn/autoanime:1.0
    container_name: autoAnime
    ports:
      - 8080:8080
    volumes:
      - ./logs:/autoAnime/logs
      - ./downloads:/autoAnime/downloads
    depends_on:
      - qbittorrent
    networks:
      animeNetwork:
        ipv4_address: 172.172.0.3

networks:
  animeNetwork:
    ipam:
      config:
        - subnet: 172.172.0.0/16