deploy_mode: local # option: local, docker
download_path: downloads
img_path: ../../autoAnimeUI/src/assets/images/anime_list
ui_url: http://127.0.0.1:5173
qb_config:
  qb_url: http://127.0.0.1:8081/
  username: admin
  password: adminadmin